### ISSUE TITLE
Check if we need to pin this to an older version of the toolkit

### ISSUE THREAD

**Issue by patudom** [cosmicds/solar-eclipse-2026#3]
This doesn't use the new compositional API for the vue toolkit because it's based on the 2024 eclipse DS, so we may need to pin this to an older version of the toolkit.

**Comment by Carifio24** [comment]
We actually don't need to change here, since the `package.json` in #2 has the toolkit version as `^0.1.3`. Normally the caret would allow minor version bumps, but since our major version is 0, the caret only matches against patch version increments. See the [relevant item](https://semver.org/#spec-item-4) in the SemVer spec, which npm follows. Thus the version that will be used is `0.1.3`, which is the last patch release before `0.2.0`.

Since this story is largely based off of the previous solar eclipse one, I say we just stick with `0.1.3` for now; we can reevaluate if there's a particular need for new toolkit features in this story.

**Comment by patudom** [comment]
Sounds good - thank you for looking into this, @Carifio24!
